local M = {}

M.kind_map = {
    File = "[File]",
    Module = "[Module]",
    Namespace = "[Namespace]",
    Package = "[Package]",
    Class = "[Class]",
    Method = "[Method]",
    Property = "[Property]",
    Field = "[Field]",
    Constructor = "[Constructor]",
    Enum = "[Enum]",
    Interface = "[Interface]",
    Function = "[Function]",
    Variable = "[Variable]",
    Constant = "[Constant]",
    String = "[String]",
    Number = "[Number]",
    Boolean = "[Boolean]",
    Array = "[Array]",
    Object = "[Object]",
    Key = "[Key]",
    Null = "[Null]",
    EnumMember = "[EnumMember]",
    Struct = "[Struct]",
    Event = "[Event]",
    Operator = "[Operator]",
    TypeParameter = "[TypeParameter]",
    Color = "[Color]",
    Control = "[Control]",
    Collapsed = "[Collapsed]",
    Folder = "[Folder]",
    Keyword = "[Keyword]",
    Reference = "[Reference]",
    Snippet = "[Snippet]",
    Text = "[Text]",
    Unit = "[Unit]",
    Unknown = "[Unknown]",
    Value = "[Value]",
}

M.kind_filter_base = {
    "Variable",
    "File",
    "Module",
    "Namespace",
    "Class",
    "Method",
    "Field",
    "Constructor",
    "Enum",
    "Function",
    "Object",
    "Key",
    "EnumMember",
    "Struct",
    "Event",
    "TypeParameter",
}

return M
