vim.g.mapleader = ' '
vim.g.material_style = 'deep ocean'

vim.opt.scrolloff = 8
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = 'a'
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.scrolloff = 8
vim.opt.numberwidth = 3
vim.opt.errorbells = false
vim.opt.hidden = true
vim.opt.undofile = true
vim.opt.undodir = os.getenv 'HOME' .. '/.vim/undo'
vim.opt.linebreak = true
vim.opt.breakindent = true
vim.opt.wrap = false
vim.opt.colorcolumn = '80'
vim.opt.signcolumn = 'yes'
vim.opt.showtabline = 0
vim.opt.termguicolors = true
vim.opt.swapfile = false
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.timeoutlen = 1000
vim.opt.hlsearch = true
vim.opt.completeopt = 'menuone,noselect'
vim.opt.cursorline = true
vim.opt.cursorlineopt = 'line'
vim.opt.cmdheight = 0
vim.opt.diffopt = 'filler,vertical,closeoff'
vim.opt.fillchars = 'diff:╱,fold:╌,foldopen:,foldclose:,msgsep:╌,eob: '
vim.opt.autoread = true
