vim.g.mapleader = " "

vim.opt.scrolloff = 8
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth=2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.scrolloff = 8
vim.opt.numberwidth = 3
vim.opt.errorbells = false
vim.opt.hidden = true
vim.opt.undofile = true
vim.opt.undodir = os.getenv( "HOME" ) .. "/.vim/undo" 
vim.opt.linebreak = true
vim.opt.wrap = true
vim.opt.signcolumn = "yes"
vim.opt.clipboard = "unnamed"
vim.opt.showtabline = 0 
vim.opt.termguicolors = true
vim.opt.swapfile = false
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.timeoutlen = 1000
vim.opt.hlsearch = false
